# Generated by Django 4.2.25 on 2025-10-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('numero_login', models.IntegerField(help_text='Número único para identificação do usuário', unique=True, verbose_name='Número de Login')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('tipo', models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('SEPARADOR', 'Separador'), ('COMPRADORA', 'Compradora'), ('ADMINISTRADOR', 'Administrador')], default='SEPARADOR', max_length=20, verbose_name='Tipo de Usuário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['numero_login'],
            },
        ),
    ]
