# Generated by Django 4.2.25 on 2025-10-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código do produto (5 dígitos numéricos)', max_length=5, unique=True)),
                ('descricao', models.CharField(help_text='Descrição do produto', max_length=255)),
                ('quantidade', models.IntegerField(help_text='Quantidade do produto')),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor unitário do produto', max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total (quantidade × valor_unitario)', max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data de última atualização')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'core_produto',
                'ordering': ['codigo'],
            },
        ),
    ]
