# Generated by Django 4.2.25 on 2025-10-25 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orcamento', models.CharField(help_text='Número único do orçamento (ex: 30567)', max_length=20, unique=True, verbose_name='Número do Orçamento')),
                ('codigo_cliente', models.CharField(max_length=50, verbose_name='Código do Cliente')),
                ('nome_cliente', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('data', models.CharField(help_text='Data no formato DD/MM/AAAA', max_length=10, verbose_name='Data do Orçamento')),
                ('logistica', models.CharField(choices=[('CORREIOS', 'Correios'), ('MELHOR_ENVIO', 'Melhor Envio'), ('ONIBUS', 'Ônibus'), ('RETIRA_LOJA', 'Retira na Loja'), ('MOTOBOY', 'Motoboy')], max_length=20, verbose_name='Tipo de Logística')),
                ('embalagem', models.CharField(choices=[('CAIXA', 'Caixa'), ('SACOLA', 'Sacola')], max_length=10, verbose_name='Tipo de Embalagem')),
                ('status', models.CharField(choices=[('EM_SEPARACAO', 'Em Separação'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EM_SEPARACAO', max_length=20, verbose_name='Status do Pedido')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início da Separação')),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('vendedor', models.ForeignKey(help_text='Vendedor responsável pelo pedido', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.IntegerField(help_text='Quantidade no orçamento', verbose_name='Quantidade Solicitada')),
                ('quantidade_separada', models.IntegerField(default=0, verbose_name='Quantidade Separada')),
                ('separado', models.BooleanField(default=False, verbose_name='Separado')),
                ('separado_em', models.DateTimeField(blank=True, null=True, verbose_name='Separado Em')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto', verbose_name='Produto')),
                ('separado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_separados', to=settings.AUTH_USER_MODEL, verbose_name='Separado Por')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero_orcamento'], name='core_pedido_numero__9fb87c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status'], name='core_pedido_status_4c9167_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['-criado_em'], name='core_pedido_criado__fb0be9_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido', 'separado'], name='core_itempe_pedido__44d92d_idx'),
        ),
    ]
