# Generated by Django 4.2.25 on 2025-10-27 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_pedido_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='em_compra',
            field=models.BooleanField(default=False, help_text='Item marcado para ser comprado', verbose_name='Em Compra'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='enviado_para_compra_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado para Compra Em'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='enviado_para_compra_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_enviados_compra', to=settings.AUTH_USER_MODEL, verbose_name='Enviado para Compra Por'),
        ),
    ]
