# Generated by Django 4.2.25 on 2025-10-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itempedido_em_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='produto_substituto',
            field=models.CharField(blank=True, help_text='Nome do produto que substituiu o original', max_length=200, null=True, verbose_name='Produto Substituto'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='substituido',
            field=models.BooleanField(default=False, help_text='Item foi substituído por outro produto', verbose_name='Substituído'),
        ),
    ]
