# Generated by Django 4.2.25 on 2025-10-27 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adicionar_campos_substituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='pedido_realizado',
            field=models.BooleanField(default=False, help_text='Compradora marcou que o pedido foi realizado', verbose_name='Pedido Realizado'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='realizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pedido Realizado Em'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido_realizado', to=settings.AUTH_USER_MODEL, verbose_name='Pedido Realizado Por'),
        ),
    ]
