# Generated by Django 4.2.25 on 2025-10-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_itempedido_pedido_realizado_itempedido_realizado_em_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['em_compra'], name='core_itempe_em_comp_ab09b1_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido_realizado'], name='core_itempe_pedido__e87ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['separado_por'], name='core_itempe_separad_2d0006_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['data_finalizacao'], name='core_pedido_data_fi_0ce531_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['vendedor'], name='core_pedido_vendedo_99fd7b_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['data_inicio'], name='core_pedido_data_in_cfedfb_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status', 'data_inicio'], name='core_pedido_status_9b5db0_idx'),
        ),
    ]
