# Generated by Django 4.2.25 on 2025-11-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#2563eb', help_text='Cor principal da marca (ex: botões, links ativos)', max_length=7, verbose_name='Cor Primária')),
                ('primary_hover', models.CharField(default='#1d4ed8', help_text='Cor de hover para elementos primários', max_length=7, verbose_name='Cor Primária Hover')),
                ('vendedor_color', models.CharField(default='#10b981', help_text='Cor para badges e elementos do papel Vendedor', max_length=7, verbose_name='Cor Vendedor')),
                ('separador_color', models.CharField(default='#8b5cf6', help_text='Cor para badges e elementos do papel Separador', max_length=7, verbose_name='Cor Separador')),
                ('compradora_color', models.CharField(default='#f97316', help_text='Cor para badges e elementos do papel Compradora', max_length=7, verbose_name='Cor Compradora')),
                ('admin_color', models.CharField(default='#ef4444', help_text='Cor para badges e elementos do papel Administrador', max_length=7, verbose_name='Cor Administrador')),
                ('success_color', models.CharField(default='#10b981', help_text='Cor para indicadores de sucesso e estados ativos', max_length=7, verbose_name='Cor Sucesso')),
                ('warning_color', models.CharField(default='#f97316', help_text='Cor para avisos e estados pendentes', max_length=7, verbose_name='Cor Aviso')),
                ('info_color', models.CharField(default='#3b82f6', help_text='Cor para informações e estados em processamento', max_length=7, verbose_name='Cor Informação')),
                ('active', models.BooleanField(default=True, help_text='Define se este tema está ativo no sistema', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Tema',
                'verbose_name_plural': 'Configurações de Tema',
                'ordering': ['-active', '-updated_at'],
            },
        ),
    ]
